version: '3.8'

services:
  linux_server1:
    build:
      context: ./docker
      dockerfile: Dockerfile.test-node
    container_name: linux_server1
    hostname: linux_server1
    restart: unless-stopped
    networks:
      - monitoring

  linux_station1:
    build:
      context: ./docker
      dockerfile: Dockerfile.test-node
    container_name: linux_station1
    hostname: linux_station1
    restart: unless-stopped
    networks:
      - monitoring

  linux_station2:
    build:
      context: ./docker
      dockerfile: Dockerfile.test-node
    container_name: linux_station2
    hostname: linux_station2
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    external: true
    name: srpcproiect_monitoring # It must match the network created by the main docker-compose
