global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporters"
    static_configs:
      - targets:
          - "linux_station1:9100"
          - "linux_station2:9100"
          - "linux_server1:9100"
        labels:
          group: "linux-nodes"

  - job_name: "kubernetes-ksm"
    static_configs:
      - targets: ["10.10.30.106:30082"]

