---
- name: Update repositories
  hosts: linux_stations
  become: yes
  tasks:
    - name: Update apt cache and upgrade packages (Debian/Ubuntu)
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Install basic dependencies (curl, gpg)
      apt:
        name:
          - curl
          - gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Update yum packages (RHEL/CentOS)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
